CREATE OR REPLACE DATABASE wallapoop;
use wallapoop;


CREATE OR REPLACE TABLE User
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PASSWD VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
)

CREATE OR REPLACE TABLE Product
(
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(256) NOT NULL,
    PRICE INT NOT NULL,
    OWNER VARCHAR(30) NOT NULL,
    FOREIGN KEY (OWNER) REFERENCES User (ID),
    PRIMARY KEY (ID)
)

